/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                'dark-charcoal': '#0e0c0c',
                'dark-mulberry': '#5f2d56',
                'dark-raspberry': '#993970',
                'raspberry-pink': '#dc4a7b',
                'light-coral': '#f78697',
                'rosewood': '#9f294e',
                'dark-redwood': '#62232f',
                'sienna': '#8f4029',
                'burnt-orange': '#c56025',
                'tangerine': '#ee8e2e',
                'pale-orange': '#fccba3',
                'tomato': '#da4e38',
                'sunflower-yellow': '#facb3e',
                'lime-green': '#97da3f',
                'kelly-green': '#4ba747',
                'forest-green': '#3d734f',
                'dark-slate-blue-1': '#314152',
                'steel-blue': '#417089',
                'sea-green': '#49a790',
                'turquoise': '#72d6ce',
                'cornflower-blue': '#5698cc',
                'medium-blue': '#5956bd',
                'dark-slate-blue-2': '#473579',
                'medium-purple': '#8156aa',
                'orchid': '#c278d0',
                'pink-lace': '#f0b3dd',
                'seashell': '#fdf7ed',
                'beige': '#d3bfa9',
                'rosy-brown': '#aa8d7a',
                'dark-brown': '#775c55',
                'black-bean': '#483b3a',
            },
        },
    },
    plugins: [],
}
